MPWW-13141: Move updated radio pill group styles to Ray
wework/ray pull request #276
Opened 2021-02-22 15:59 UTC by maksymnado

JIRA: [MPWW-13141](https://jira.weworkers.io/browse/MPWW-13141)

2021-02-22 16:59 UTC, bennybennett approved these changes
Please get Dana Ballasy's QA, but this looks good from a code standpoint.

2021-02-22 21:35 UTC, maniator requested changes
[REMOVED]

2021-02-23 07:59 UTC, maksymnado commented
> Please delete

2021-02-23 08:00 UTC, maksymnado commented
> Please delete

@maniator can you please clarify what I should delete?

2021-02-23 09:15 UTC, MariiaPashchevska approved these changes

2021-02-24 13:31 UTC, bennybennett commented
@maksymnado Please disregard any comments from @maniator. Sorry about the confusion.

2021-02-24 13:55 UTC, jmiles90 approved these changes

2021-02-24 14:00 UTC, designjockey commented
@bennybennett seems like I’m still in the maintainers list for this repo and am getting notifications as well. Even though this repo is open source, probably want to remove me from the maintainers list.

2021-02-24 15:31 UTC, bennybennett commented
@designjockey You are still set as Maintainer. Please set all other Members as Maintainers as I will change yours.

2021-02-24 15:57 UTC, designjockey commented
@bennybennett I've made you the maintainer and removed myself from the group...

![Screen Shot 2021-02-24 at 10 55 43 AM](https://user-images.githubusercontent.com/916262/109027600-f901a400-768e-11eb-91d0-10651ef28b77.png)

2021-03-09 14:59 UTC, merged